on:
  issue_comment:
    types: [created, deleted]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@master # use the master branch so that
      # I don't have to remember the release version
      - name: Test Python script
        id: pythontest
        uses: bytrangle/python-github-action@main
        with:
          min_total_comments: 10
          reacted_comment_count: 3
